-- H2 Syntax
INSERT INTO REBIND_ROLE VALUES (1, 'ADMIN');

INSERT INTO REBIND_ROLE VALUES (2, 'UNCONFIRMED_USER');

INSERT INTO REBIND_ROLE VALUES (3, 'CONFIRMED_USER');

INSERT INTO REBIND_ROLE VALUES (4, 'USER');